baseURL: "https://randoneering.tech"
title: Randoneering, LLC
paginate: 5
theme: charlolamode

menu:
  main:
    - name: Contact
      url: /contact/
      weight: 30
    - name: Blog
      url: /blog/
      weight: 20
    - name: Hire Me
      url: /services/
      weight: 10

params:
  author: Justin@Randoneering

  defaultTheme: dark
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    title: Randoneering, LLC
    description: Justin Frye | Founding Randoneer (TM)


      Fractional Infrastructure Services for Startups and Small Businesses

    imageUrl: "/images/randoneering_logo_only.jpg"

    #imageTitle:
    #imageWidth: 375
    #imageHeight: 350
    buttons:
      - name: Donate to my ALF Fundraiser!
        url: https://liverlifechallenge.org/chicago/support/#jfrye
  mainSections:
    - blog
  socialIcons:
    - name: mastodon
      url: "https://hachyderm.io/@randoneering"
    - name: github
      url: "https://github.com/randoneering"
    - name: linkedin
      url: "https://www.linkedin.com/in/justin-frye-b4b14763/"

  assets:
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
