name: CI-HUGO
run-name: Deploy hugo site
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    env:
      HUGO_VERSION: 0.137.1
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initialize the ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb   

      - name: Build the website
        run: hugo

      - name: Scan the host key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          SSH_PORT="${DEPLOY_PORT:-22}"
          ssh-keyscan -p "$SSH_PORT" -H -T 10 "$DEPLOY_SERVER" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}

      - name: Deploy the website
        run: |
          SSH_PORT="${DEPLOY_PORT:-22}"
          rsync -avx --delete --exclude '.ssh' -e "ssh -p $SSH_PORT" public/ "$DEPLOY_USERNAME@$DEPLOY_SERVER:./"
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
